# Generated by Django 4.0.3 on 2022-05-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truecar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('city', models.DateField()),
                ('pincode', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='truecar/images'),
        ),
    ]
