# Generated by Django 4.0.3 on 2022-05-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truecar', '0002_register_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='pincode',
            field=models.CharField(max_length=50),
        ),
    ]
